"""initial_user_and_cache_tables

Revision ID: f236f1be0d49
Revises: 
Create Date: 2026-02-02 11:47:31.158122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f236f1be0d49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False, comment='Unique GitHub user ID'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='GitHub username (login)'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='User email (may be private)'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='Display name'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='GitHub avatar URL'),
    sa.Column('bio', sa.Text(), nullable=True, comment='User biography'),
    sa.Column('company', sa.String(length=255), nullable=True, comment='Company name'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='User location'),
    sa.Column('blog', sa.String(length=500), nullable=True, comment='Blog or website URL'),
    sa.Column('public_repos', sa.Integer(), nullable=False, comment='Number of public repositories'),
    sa.Column('followers', sa.Integer(), nullable=False, comment='Number of followers'),
    sa.Column('following', sa.Integer(), nullable=False, comment='Number of users following'),
    sa.Column('access_token', sa.String(length=255), nullable=False, comment='GitHub OAuth access token (SENSITIVE)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Account creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.Column('last_login_at', sa.DateTime(), nullable=False, comment='Last login timestamp'),
    sa.PrimaryKeyConstraint('id'),
    comment='GitHub OAuth authenticated users'
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index('ix_users_github_username', 'users', ['github_id', 'username'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cached_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User who owns this cache entry'),
    sa.Column('cache_key', sa.String(length=100), nullable=False, comment="Cache key identifier (e.g., 'user_stats', 'languages')"),
    sa.Column('data', sa.JSON(), nullable=False, comment='Cached JSON data'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Cache expiration timestamp'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Cache creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cache_key', name='uq_user_cache_key'),
    comment='Cached GitHub API responses'
    )
    op.create_index(op.f('ix_cached_data_cache_key'), 'cached_data', ['cache_key'], unique=False)
    op.create_index('ix_cached_data_expires', 'cached_data', ['expires_at'], unique=False)
    op.create_index(op.f('ix_cached_data_expires_at'), 'cached_data', ['expires_at'], unique=False)
    op.create_index(op.f('ix_cached_data_user_id'), 'cached_data', ['user_id'], unique=False)
    op.create_index('ix_cached_data_user_key', 'cached_data', ['user_id', 'cache_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cached_data_user_key', table_name='cached_data')
    op.drop_index(op.f('ix_cached_data_user_id'), table_name='cached_data')
    op.drop_index(op.f('ix_cached_data_expires_at'), table_name='cached_data')
    op.drop_index('ix_cached_data_expires', table_name='cached_data')
    op.drop_index(op.f('ix_cached_data_cache_key'), table_name='cached_data')
    op.drop_table('cached_data')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_github_username', table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
